---
title: "Text Mining Shakespeare's First Folio"
author: "Eric Kammers"
date: "November 27, 2017"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE,warning=FALSE, include=FALSE}
library(tm)
library(SnowballC)
library(slam)
library(wordcloud)
library(RColorBrewer)
library(reshape2)
library(ggplot2)
library(TailRank)
library(lsa)
library(ggrepel)
library(knitr)
library(cluster)
library(ggfortify)
```

<!-- Download File -->
```{r, echo=FALSE, warning=FALSE}
setwd("~/Shakespeare Analysis") # set working directory
TEXTFILE = "data/pg100.txt" 

if (!file.exists(TEXTFILE)) {   # download shakespeare complete works
       dir.create(dirname(TEXTFILE), FALSE)
       download.file("http://www.gutenberg.org/cache/epub/100/pg100.txt", destfile = TEXTFILE)
}

shakespeare <- readLines(TEXTFILE) # read in text file line-by-line
head(shakespeare)
shakespeare <- paste(shakespeare, collapse = " ") # combine all lines
```

```{r, echo=FALSE, warning=FALSE}
copyright <- "<<THIS ELECTRONIC VERSION OF THE COMPLETE WORKS OF WILLIAM SHAKESPEARE IS COPYRIGHT 1990-1993 BY WORLD LIBRARY, INC., AND IS PROVIDED BY PROJECT GUTENBERG ETEXT OF ILLINOIS BENEDICTINE COLLEGE WITH PERMISSION. ELECTRONIC AND MACHINE READABLE COPIES MAY BE DISTRIBUTED SO LONG AS SUCH COPIES (1) ARE FOR YOUR OR OTHERS PERSONAL USE ONLY, AND (2) ARE NOT DISTRIBUTED OR USED COMMERCIALLY. PROHIBITED COMMERCIAL DISTRIBUTION INCLUDES BY ANY SERVICE THAT CHARGES FOR DOWNLOAD TIME OR FOR MEMBERSHIP.>>"
copyright
```

<!-- Format & Clean Data -->
```{r, echo=FALSE, warning=FALSE}
shakespeare <- strsplit(shakespeare, "<<[^>]*>>")[[1]] # removes copyright material
shakespeare <- shakespeare[-c(1,2,length(shakespeare))] # extraneous info
```

<!-- Organize Data -->
```{r, echo=FALSE, warning=FALSE}
# Identify where Dramatis Personae are in data sctructure
dramatis.personae <- grep("Dramatis Personae", shakespeare, ignore.case = TRUE)

plays <- vector(mode="list")    # reduce down to just plays
for(i in seq(length(dramatis.personae))){
  plays[[i]] <- shakespeare[dramatis.personae[i]:(dramatis.personae[i]+5)]
}
shakespeare <- plays; rm(plays) # reduce down to just plays

shakespeare[[3]][6] <- strsplit(shakespeare[[3]][6], "      ")[[1]][1] # remove "THE COMEDY OF ERRORS"
shakespeare[[4]][1] <- "THE COMEDY OF ERRORS"

# extract Play titles from Dramatis Personae's
for(i in seq(length(shakespeare))){
  ex <- strsplit(shakespeare[[i]][1], " by William Shakespeare")[[1]][1]
  ex <- strsplit(ex, "  ")[[1]]; ex <- ex[length(ex)]                 # remove date published
  ex <- strsplit(ex, " ")[[1]]; if(ex[1]==""){ex <- ex[2:length(ex)]} # remove extraneous spaces
  shakespeare[[i]][1] <- paste(ex, collapse = " ")
}
```

<!-- Organize by Act w/ All Plays (i.e. Act I all plays, Act II all plays, etc.) -->
```{r, echo=FALSE, warning=FALSE}
# Organize text by each act
acts <- vector(mode="list")
for(i in (seq(5))){
  act <- NULL
  for(j in seq(length(shakespeare))){
    act <- cbind(act, shakespeare[[j]][i+1])
  }
  acts[[i]] <- as.vector(act)
}
```

<!-- Organize by Play w/ All Acts (i.e. Play I all Acts, Play II all Acts, etc.) -->
```{r, echo=FALSE, warning=FALSE}
# organize text by each play with all acts
plays <- vector(length=length(shakespeare))
for(i in seq(length(shakespeare))){
  plays[i] <- paste(shakespeare[[i]][2:5],collapse = '')
}
```

<!-- Color Coding & Ordering -->
```{r, echo=FALSE, warning=FALSE}
# Vector of All plays by Title in original order
play.title <- NULL
for(i in seq(length(shakespeare))){
  play.title <- cbind(play.title,shakespeare[[i]][1])
}
play.title <- as.vector(play.title)

# play types and color coding
Play.Type <- c('c','t','c','c','t','t','t','h','h','h','h','h','h','h','h','t','t','c','t','c','c','c','c','c','t','h','h','t','c','c','t','t','t','c','c','c')
color.code <- ifelse(Play.Type == 'c','red',ifelse(Play.Type == 't','blue','green'))
Play.Type <- ifelse(Play.Type == 'c','Comedy',ifelse(Play.Type == 't','Tragedy','History'))
Play.Type
```

<!--Order by Play Category: Comedy, History, Tragedy -->
```{r, echo=FALSE, warning=FALSE}
# by each act
acts.temp <- vector(mode = "list")
for(i in (seq(5))){
  acts.temp[[i]] <- acts[[i]][order(Play.Type)]
}
acts <- acts.temp

# play with all acts
plays <- plays[order(Play.Type)]

# play titles
play.title <- play.title[order(Play.Type)]

color.code <- color.code[order(Play.Type)]
Play.Type <- Play.Type[order(Play.Type)]
Play.Type
```


<!-- TEXT TO TERM-DOCUMENT MATRIX -->
```{r, echo=TRUE, warning=FALSE}
text2TDM <- function(text){
  
  doc.vec <- VectorSource(as.vector(text))
  doc.corpus <- Corpus(doc.vec)
  
  doc.corpus <- tm_map(doc.corpus, content_transformer(tolower))
  doc.corpus <- tm_map(doc.corpus, removePunctuation)
  doc.corpus <- tm_map(doc.corpus, removeNumbers)
  doc.corpus <- tm_map(doc.corpus, removeWords, stopwords("english"))
  
  doc.corpus <- tm_map(doc.corpus, stemDocument)
  doc.corpus <- tm_map(doc.corpus, stripWhitespace)
  
  TDM <- TermDocumentMatrix(doc.corpus)
  
  return(TDM)
}
```

<!-- Standardize TDM based on word proportion -->
```{r, echo=FALSE, warning=FALSE}
std.TDM <- function(TDM){ # , sparsity
  for(i in seq(ncol(TDM))){
    if(colSums(TDM)[i]==0){
      TDM[,i] <- TDM[,i]
    } else{
      TDM[,i] <- TDM[,i]/colSums(TDM)[i]
    }
  }
  
  # TDM <- removeSparseTerms(TDM, sparsity)
  TDM.dense <- as.matrix(TDM)
  return(TDM.dense)
} # NOTE: Normalized based on COLUMNS
```


<!-- Compare by each play -->
```{r, echo=FALSE, warning=FALSE}
# Compare by each play
plays <- text2TDM(plays)

knitr::kable(
  as.matrix(plays)[1:10,], 
  caption = "TDM Comparison of All Acts in Each Play between Each Term Used"
)

```

## Preparing Data for Clustering
<!-- Normalization and Sparse Term Removal -->
```{r, echo=FALSE, warning=FALSE}
std.mat <- std.TDM(as.matrix(plays))

z <- which(rowSums(as.matrix(std.mat!=0))==1)

std.mat.z <- std.mat[-z,]
```


## Clustering and Visualising
```{r, echo=FALSE, warning=FALSE}
svd.prep <- scale(t(std.mat.z), center = TRUE, scale = TRUE)

plays.svd <- svd(svd.prep)
```


```{r, echo=FALSE, warning=FALSE, fig.align="center"}
# Barplot of first 6 PC's
melted <- cbind(Play.Type, melt(((svd.prep)%*%(plays.svd$v))[,1:6]))
ggplot(data=melted) + 
  theme_bw() + ggtitle('Principal Components') +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_bar(aes(x=Docs, y=value, fill=Play.Type), stat="identity") +
  labs(x="Index",y="Value", fill="Play Type") +
  facet_wrap(~Var2)
```

```{r, echo=FALSE, warning=FALSE, fig.align="center"}
# Plot first two PC's
points <- data.frame(((svd.prep)%*%(plays.svd$v))[,1:9])
colnames(points) <- paste("PC",seq(dim(points)[2]),sep="")

ggplot(points, aes(x = PC1, y = PC2, color = Play.Type)) + theme_bw() + ggtitle('Shakespeares Plays - 2D Space') + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  geom_point(data = points, aes(x = PC1, y = PC2, color = Play.Type)) + 
  labs(x="PC1",y="PC2", color = "Play Type")

```

```{r, echo=FALSE, warning=FALSE, fig.align="center"}
#Clustering PC1 & PC2 based on partitioning around medoids
# cluster based on Partitioning Around Medoids
medoids <- pam(points[,1:2], 3)

# plot from from clustering
points <- data.frame(medoids$data)
Cluster <- paste("Cluster",medoids$clustering)
ggplot(points, aes(x = PC1, y = PC2, color = Cluster)) + 
  theme_bw() + ggtitle('Shakespeares Plays - Partitioning Around Medoids') +
  stat_ellipse(geom = "polygon", alpha = 0.5, aes(fill = Cluster)) + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  geom_point(data = points, aes(x = PC1, y = PC2))
```

### Cluster 1 - Primarily Tragedies, Lower Right
```{r, echo=FALSE, warning=FALSE}
knitr::kable(
  as.matrix(cbind(play.title[which(medoids$clustering==1)],
                  Play.Type[which(medoids$clustering==1)]))
)
```

### Cluster 2 - Primarily Comedies, Upper Right
```{r, echo=FALSE, warning=FALSE}
knitr::kable(
  as.matrix(cbind(play.title[which(medoids$clustering==2)],
                  Play.Type[which(medoids$clustering==2)]))
)
```


### Cluster 3 - Primarily Histories, Center Left
```{r, echo=FALSE, warning=FALSE}
knitr::kable(
  as.matrix(cbind(play.title[which(medoids$clustering==3)],
                  Play.Type[which(medoids$clustering==3)]))
)
```

```{r, echo=FALSE, warning=FALSE}
## see which words are common among plays in each cluster
clust1 <- std.mat.z[,which(medoids$clustering==1)]; clust1 <- clust1[which(rowSums(clust1!=0)==dim(clust1)[2]),]

clust2 <- std.mat.z[,which(medoids$clustering==2)]; clust2 <- clust2[which(rowSums(clust2!=0)==dim(clust2)[2]),]

clust3 <- std.mat.z[,which(medoids$clustering==3)]; clust3 <- clust3[which(rowSums(clust3!=0)==dim(clust3)[2]),]

words.1 <- rownames(clust1)
words.2 <- rownames(clust2)
words.3 <- rownames(clust3)

w1Distinct <- setdiff(words.1, c(words.2,words.3))
w2Distinct <- setdiff(words.2, c(words.1,words.3))
w3Distinct <- setdiff(words.3, c(words.1,words.2))
rm(words.1, words.2, words.3)

clust1 <- clust1[w1Distinct,]
clust2 <- clust2[w2Distinct,]
clust3 <- clust3[w3Distinct,]
```

```{r, echo=FALSE, warning=FALSE, fig.align="center", fig.width=10}
# Cluster 1: 1-32
ggplot(data=data.frame(words = w1Distinct[order(rowMeans(clust1), decreasing = TRUE)][1:32],
                       Y = sort(rowMeans(clust1), decreasing = TRUE)[1:32]), aes(x=reorder(words, -Y), y=Y)) +
       geom_bar(stat="identity") +
       theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5)) +
       scale_y_continuous(labels = scales::percent) +
       labs(x="Terms",y="Average Percent Usage", title = "Cluster 1 Distinct Terms: 1-32")
```

```{r, echo=FALSE, warning=FALSE, fig.align="center", fig.width=10}
# Cluster 1: 33-64
ggplot(data=data.frame(words = w1Distinct[order(rowMeans(clust1), decreasing = TRUE)][33:64],
                       Y = sort(rowMeans(clust1), decreasing = TRUE)[33:64]), aes(x=reorder(words, -Y), y=Y))+
       geom_bar(stat="identity") +
       theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5)) +
       scale_y_continuous(labels = scales::percent) +
       labs(x="Terms",y="Average Percent Usage", title = "Cluster 1 Distinct Terms: 33-64")
```

```{r, echo=FALSE, warning=FALSE, fig.align="center", fig.width=10}
# Cluster 2
ggplot(data=data.frame(words = w2Distinct[order(rowMeans(clust2), decreasing = TRUE)],
                       Y = sort(rowMeans(clust2), decreasing = TRUE)), aes(x=reorder(words, -Y), y=Y)) + 
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(labels = scales::percent) +
  labs(x="Terms",y="Average Percent Usage", title = "Cluster 2 Distinct Terms")
```

```{r, echo=FALSE, warning=FALSE, fig.align="center", fig.width=10}
# Cluster 3: 1-43
ggplot(data=data.frame(words = w3Distinct[order(rowMeans(clust3), decreasing = TRUE)][1:43],
                       Y = sort(rowMeans(clust3), decreasing = TRUE)[1:43]), aes(x=reorder(words, -Y), y=Y)) + 
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(labels = scales::percent) +
  labs(x="Terms",y="Average Percent Usage", title = "Cluster 3 Distinct Terms: 1-43")
```

```{r, echo=FALSE, warning=FALSE, fig.align="center", fig.width=10}
# Cluster 3: 44-86
ggplot(data=data.frame(words = w3Distinct[order(rowMeans(clust3), decreasing = TRUE)][44:86],
                       Y = sort(rowMeans(clust3), decreasing = TRUE)[44:86]), aes(x=reorder(words, -Y), y=Y))+
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(labels = scales::percent) +
  labs(x="Terms",y="Average Percent Usage", title = "Cluster 3 Distinct Terms: 44-86")
```

```{r, echo=FALSE, warning=FALSE, fig.align="center", fig.width=10}
# Cluster 3 second half
ggplot(data=data.frame(words = w3Distinct[order(rowMeans(clust3), decreasing = TRUE)][87:129],
                    Y = sort(rowMeans(clust3), decreasing = TRUE)[87:129]), aes(x=reorder(words, -Y), y=Y)) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(labels = scales::percent) +
  labs(x="Terms",y="Average Percent Usage", title = "Cluster 3 Distinct Terms: 87-129")
```

```{r, echo=FALSE, warning=FALSE, fig.align="center", fig.width=10}
# Cluster 3 second half
ggplot(data=data.frame(words = w3Distinct[order(rowMeans(clust3), decreasing = TRUE)][130:172],
                    Y = sort(rowMeans(clust3), decreasing = TRUE)[130:172]), aes(x=reorder(words, -Y), y=Y)) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(labels = scales::percent) +
  labs(x="Terms",y="Average Percent Usage", title = "Cluster 3 Distinct Terms: 130-172")
```

